cache:
  paths:
      - vendor/
before_script:
- apt-get update -yqq
- apt-get install git -yqq
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

test:7.0:
  image: php:7.0
  script:
  - php composer.phar test  